### INFORMATIONS ###

# Repository : https://github.com/matthieu-locussol/Traycer
# Builds     : https://travis-ci.com/matthieu-locussol/Traycer

language:
    cpp

matrix:
    include:
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode11
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode10
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode9
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode8
        - env:
            - BUILD_TYPE=Release
          os: osx
          osx_image: xcode7.3

install:
    - mv Build/install_osx.sh .
    - sudo ./install_osx.sh
    - cd Build # Traycer/Build
    - sudo mkdir -p Application/Binaries/
    - sudo mv Application/Traycer Application/Binaries/.
    - sudo mv Application Traycer
    - sudo zip -r Traycer:${TRAVIS_OS_NAME}-${TRAVIS_OSX_IMAGE}.zip Traycer

script:
    - ./Tests/golTests
    - curl -T Traycer*.zip ftp://${FTP_USERNAME}:${FTP_PASSWORD}@${FTP_HOSTNAME}/Traycer_Releases/latest/osx/